<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<OutputType>Exe</OutputType>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<IsPackable>false</IsPackable>
	<IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
	<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
	<PackageReference Include="xunit.v3" Version="3.2.2" />
	<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\WfpChatBotWebApp\WfpChatBotWebApp.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Using Include="Xunit" />
  </ItemGroup>

</Project>
